set backupcopy=yes
source ~/.vim/general.vim
source ~/.vim/keybindings.vim
source ~/.vim/behavior.vim
source ~/.vim/vundle.vim
source ~/.vim/behavior.vim
source ~/.vim/languages.vim
source ~/.vim/style.vim
source ~/.vim/config.vim
