#! /bin/sh

sxhkd &

if [ `hostname` = shibusa ]; then
	# assign the monitors
	bspc monitor DP-0 -d 4 5 6
	bspc monitor DP-4 -d 1 2 3

	# then swap so the primary is on the right
	bspc monitor DP-0 -s DP-4
else
		bspc monitor -d 1 2 3 4 5 6 7 8 9 10
fi

if [ -f "~/MEGA/Photos/background.jpg" ]; then
	feh --bg-center ~/MEGA/Photos/background.jpg
fi

bspc config border_width         0
bspc config window_gap           12
bspc config top_padding 40

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Firefox desktop='^4' focus=on
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
